---
  version: '3.6'
  services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
      container_name: elasticsearch-web
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      ports:
        - "9200:9200"
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health | grep -v '\"status\":\"red\"'"]
      networks:
        - envoymesh
        
    kibana:
      image: docker.elastic.co/kibana/kibana:7.6.0
      container_name: kibana-web
      environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
      ports:
        - "5601:5601"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://kibana:5601/"]
      depends_on:
        - elasticsearch
      networks:
        - envoymesh
    
    apm-server:
      image: docker.elastic.co/apm/apm-server:7.6.0
      container_name: apm-server
      ports:
        - "8200:8200"
      environment:
        - output.elasticsearch.hosts=['http://elasticsearch:9200']
        - apm-server.host="0.0.0.0:8200"
        - setup.kibana.host="kibana:5601"
      command: apm-server -e -d "*" -E apm-server.host="0.0.0.0:8200" -E apm-server.expvar.enabled=true
      depends_on:
        - elasticsearch
        - kibana
      healthcheck:
        test: ["CMD", "curl", "-f" ,"http://apm-server:8200/"]
      networks:
        - envoymesh
  
    mongodb-web:
      image: mongo:4.4.10
      container_name: mongodb-web
      networks:
        envoymesh:
          aliases:
            - mondodb-web
      ports:
        - "27017:27017"
      expose: 
        - "27017"
    
    api-envoy:
      container_name: api-envoy
      build:
        context: .
        dockerfile: ./envoy/Dockerfile
      volumes:
        - ./envoy/api-envoy.yaml:/etc/api-envoy.yaml
      expose:
        - "3000"
      networks:
        - envoymesh
      ports:
        - "3000:3000"
        - "9901:9901"
    
    auth-service:
      container_name: auth-service
      build: ./auth
      command: ["npm", "run", "apm"]
      ports:
        - "3001:3001"
      environment:
        - FASTIFY_PORT=3001
      volumes:
        - ./auth/:/usr/src/app
        - /usr/src/app/node_modules
      links:
        - apm-server
        - mongodb-web
      networks:
        - envoymesh
  
    tickets-service:
      container_name: tickets-service
      build: ./tickets
      command: ["npm", "run", "apm"]
      ports:
        - "3002:3002"
      environment:
        - FASTIFY_PORT=3002
      volumes:
        - ./tickets/:/usr/src/app
        - /usr/src/app/node_modules
      links:
        - apm-server
        - mongodb-web
      networks:
        - envoymesh

    users-service:
      container_name: users-service
      build: ./users
      command: ["npm", "run", "apm"]
      ports:
        - "3003:3003"
      environment:
        - FASTIFY_PORT=3003
      volumes:
        - ./users/:/usr/src/app
        - /usr/src/app/node_modules
      links:
        - apm-server
        - mongodb-web
      networks:
        - envoymesh

  networks:
    envoymesh: {}